name: ludo

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
#  get: ^4.6.5
  lottie: ^2.6.0
  image_picker: ^0.8.7
#  image_picker: ^1.0.4
  shimmer: ^3.0.0
  add_to_cart_animation: ^2.0.3
  url_launcher: ^6.1.12
  flutter_share: ^2.0.0
  google_fonts: ^5.1.0
  upi_india: ^3.0.1
  just_audio: ^0.9.29
  provider: ^6.0.3
  simple_ripple_animation: ^0.0.3
  audioplayers: ^5.1.0
  dotted_border: ^2.0.0+3
  http:



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/button/
    - assets/images/
    - assets/images/dice/
    - assets/images/crown/
    - assets/sounds/
    - assets/font/Acme-Regular.ttf
    - assets/font/Righteous-Regular.ttf

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900


    - family: Acme
      fonts:
        - asset: assets/font/Acme-Regular.ttf
          weight: 400

    - family: Righteous
      fonts:
        - asset: assets/font/Righteous-Regular.ttf
          weight: 400







